agents:
  queue: "aws"

steps:
  - label: ":bash: Lint"
    command: "do/lint"

  - label: ":hammer: Unit Test"
    commands:
      - "do/test"
      - "do/scan"
    key: "test"
    artifact_paths:
      - "test-output/test/results/*.xml"
    timeout_in_minutes: ${DEFAULT_TIMEOUT}
    retry:
      automatic:
        - exit_status: 1
          limit: 2

  - label: ":gear: :debian: Build Debian Package"
    commands:
      - "do/build"
      - "do/package"
    key: "package"
    artifact_paths:
      - "build-output/*.deb"
    timeout_in_minutes: ${DEFAULT_TIMEOUT}
    retry:
      automatic:
        - exit_status: 1
          limit: 2

  - label: ":aws: Publish to S3 APT Repo"
    commands:
      - "do/package --docker-only"
      - "do/publish"
    branches: "master develop release-*"
    depends_on:
      - "test"
      - "package"
    allow_dependency_failure: false
    key: "publish"
    timeout_in_minutes: ${DEFAULT_TIMEOUT}
    retry:
      automatic:
        - exit_status: 1
          limit: 2
    soft_fail:
      - exit_status: 123

  - label: ":rocket: Test Results"
    plugins:
      - junit-annotate#v1.9.0:
          artifacts: test-output/test/results/*.xml
          report-slowest: 6
    depends_on:
      - "test"
    allow_dependency_failure: true
    soft_fail:
      - exit_status: 1
