steps:
  - label: ":gear: Build"
    commands:
      - "pwd"
      - "do/build"
    key: "build"
    agents:
      queue: "aws"

  - label: ":hammer: Unit Test"
    commands:
      - "do/test"
    depends_on:
      - "build"
    allow_dependency_failure: false
    key: "test"
    artifact_paths:
      - "build/test/results/*.xml"
    agents:
      queue: "aws"

  - label: ":microscope: Sonar Scan"
    commands:
      - "do/private/scan"
    depends_on:
      - "test"
    allow_dependency_failure: false
    key: "scan"
    agents:
      queue: "aws"

  - label: ":rocket: Test Results"
    plugins:
      - junit-annotate#v1.9.0:
          artifacts: build/test/results/*.xml
          report-slowest: 6
    depends_on:
      - "test"
    allow_dependency_failure: true
    soft_fail:
      - exit_status: 1
    agents:
      queue: "aws"