ARG PROJECT_REPO
ARG DOCKER_VER_IMG
FROM ${PROJECT_REPO}:thirdparty-${DOCKER_VER_IMG}

ARG PROJECT_REPO
ARG GIT_BRANCH
ARG GIT_COMMIT

ENV PROJECT_REPO=${PROJECT_REPO}
ENV GIT_BRANCH=${GIT_BRANCH}
ENV GIT_COMMIT=${GIT_COMMIT}
