#!/bin/bash

RESULT=0
mapfile -t TEST_EXECS < <(find test -type f -name "*_tests")
if [ -z "${TEST_EXECS[0]}" ]; then
    echo "No Tests to be found"
    exit
fi

echo "Running the following tests: ${TEST_EXECS[*]}"

for EXEC in "${TEST_EXECS[@]}"; do
    echo "Running test '${EXEC}'..."
    NAME=$(basename "${EXEC}" | sed -r -n "s/(.*)_tests/\1/p")
    ${EXEC} --gtest_filter="-*Gpu*" --gtest_output="xml:test/results/${NAME}.xml" --gtest_color=yes --gtest_shuffle
    THIS_TEST_RESULT=$?
    if [ "${THIS_TEST_RESULT}" -ne 0 ]; then RESULT=${THIS_TEST_RESULT}; fi
done

exit "${RESULT}"