#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -z "$SONAR_TOKEN" ]; then
  echo "Building without sonar wrapper"
  ${SCRIPT_DIR}/build_for_test_cmd
  exit $?
else
  echo "Building with sonar wrapper"
  build-wrapper-linux-x86-64 --out-dir "build/bw-output" ${SCRIPT_DIR}/build_for_test_cmd
  exit $?
fi
