#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd "${SCRIPT_DIR}/../.." > /dev/null 2>&1 || exit 1

grep -rl '^#!/.*sh' . | while read -r file ; do
  [[ $file =~ \.git ]] && continue
  [[ $file =~ init\.d ]] && continue
  [[ $file =~ vendor ]] && continue
  [[ $file =~ plugins ]] && continue
  [[ $file =~ node_modules ]] && continue

  echo "Processing $file"
  # echo $PWD
  docker run --rm -v "$PWD:/mnt" koalaman/shellcheck --external-sources --shell=bash --exclude=SC2086,SC2034 "$file"
  echo -e "Ok.\\n"
done