#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd "${SCRIPT_DIR}/../.." > /dev/null 2>&1 || exit 1
source "${SCRIPT_DIR}/script_utils"

configure_environment

echo "Scanning repo '${PROJECT_REPO}', branch '${GIT_BRANCH}', commit '${GIT_COMMIT}'"

echo "+++ :sonarcloud: Scan project"
docker run \
      --rm  \
      --tty \
      --volume "$(pwd):/app" \
      "${PROJECT_REPO}:build-${GIT_TAG}" \
      "do/private/docker_scan"

exit_on_fail $?

popd > /dev/null 2>&1
