#!/usr/bin/env sh
set -e
#=============================================================================
echo "Generating udev rules for access to usb lasers"

RULES_FILE=/etc/udev/rules.d/90-cyusb.rules

cat <<EOT >> ${RULES_FILE}
#Rules for the cypress usb
SUBSYSTEM=="usb", ATTR{idVendor}=="04b4", MODE:="0666", TAG+="uaccess", TAG+="udev-acl"
EOT
echo "Udev rules written to ${RULES_FILE}"
ldconfig
exit 0