#!/usr/bin/env sh

set -e

# Do nothing on purge, currently all files are removed with a standard remove.
if [ $1 = 'purge' ]
then
  exit 0
fi

#=============================================================================
echo "Removing udev rules for access to usb lasers"

RULES_FILE=/etc/udev/rules.d/90-cyusb.rules

rm ${RULES_FILE}

echo "Removed ${RULES_FILE}"

echo "Removing ldconf file."
rm /etc/ld.so.conf.d/cyusbserial.conf
ldconfig

#=============================================================================
#echo "Removing blacklist for ftdi_sio and usbserial"
#
#BLACKLIST_FILE=/etc/modprobe.d/ftd2xx-blacklist.conf
#
#rm ${BLACKLIST_FILE}
#
#echo "Removed ${BLACKLIST_FILE}"

exit 0