#!/usr/bin/env sh

# Based on rules written by V. Radhakrishnan ( rk@atr-labs.com )

set -e
#=============================================================================
echo "Generating udev rules for access to usb lasers"

RULES_FILE=/etc/udev/rules.d/90-cyusb.rules

cat <<EOT >> ${RULES_FILE}
#Rules for the cypress usb
SUBSYSTEM=="usb", ATTR{idVendor}=="04b4", MODE:="0666", TAG+="uaccess", TAG+="udev-acl"
EOT
(udevadm control --reload-rules && udevadm trigger) || echo "Failed to reload udev rules."
echo "Udev rules written to ${RULES_FILE}"

echo "Writing ldconf file."
echo "/usr/lib/CyUSBSerial" > /etc/ld.so.conf.d/cyusbserial.conf

ldconfig
exit 0
